// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3PP6fOoDBZsISn4bM2w61dT2zPhTgysg',
    appId: '1:969442850671:web:d955afe6a2b56db6f3da9a',
    messagingSenderId: '969442850671',
    projectId: 'flutter-quran-fab7e',
    authDomain: 'flutter-quran-fab7e.firebaseapp.com',
    storageBucket: 'flutter-quran-fab7e.appspot.com',
    measurementId: 'G-9KSMGMDR6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABobXyPf2PSH50y36TXI-a4UHiRvg3Vts',
    appId: '1:969442850671:android:8292b4c15149ffb0f3da9a',
    messagingSenderId: '969442850671',
    projectId: 'flutter-quran-fab7e',
    storageBucket: 'flutter-quran-fab7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9dvPDqCrcRUWWxHIrm0Dz5C1lg6nJdvk',
    appId: '1:969442850671:ios:755749d2ee1a8fecf3da9a',
    messagingSenderId: '969442850671',
    projectId: 'flutter-quran-fab7e',
    storageBucket: 'flutter-quran-fab7e.appspot.com',
    iosBundleId: 'com.example.flutterQuran',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9dvPDqCrcRUWWxHIrm0Dz5C1lg6nJdvk',
    appId: '1:969442850671:ios:755749d2ee1a8fecf3da9a',
    messagingSenderId: '969442850671',
    projectId: 'flutter-quran-fab7e',
    storageBucket: 'flutter-quran-fab7e.appspot.com',
    iosBundleId: 'com.example.flutterQuran',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3PP6fOoDBZsISn4bM2w61dT2zPhTgysg',
    appId: '1:969442850671:web:b44b2308c0ebd67ef3da9a',
    messagingSenderId: '969442850671',
    projectId: 'flutter-quran-fab7e',
    authDomain: 'flutter-quran-fab7e.firebaseapp.com',
    storageBucket: 'flutter-quran-fab7e.appspot.com',
    measurementId: 'G-XKKHCFM110',
  );

}